package paxchecker.GUI;

import paxchecker.*;

/**
 *
 * @author SunnyBat
 */
public class Setup extends javax.swing.JFrame {

  public java.util.ArrayList<ExtraPhonePanel> extraPhonePanelList = new java.util.ArrayList<>();

  /**
   * Creates new form Setup
   */
  public Setup() {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        initComponents();
        customComponents();
        setVisible(true);
      }
    });
  }

  private void customComponents() {
    setTitle("PAXChecker Setup v" + PAXChecker.VERSION);
    if (Browser.getVersionNotes() != null) {
      setPatchNotesText(Browser.getVersionNotes());
    }
    long tS = System.nanoTime();
    jSlider1.setValue(SettingsHandler.getDelayTime());
    jCheckBox1.setSelected(SettingsHandler.getCheckPaxWebsite());
    jCheckBox2.setSelected(SettingsHandler.getCheckShowclix());
    if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
      jButton1.setEnabled(false);
    }
    jCheckBox3.setSelected(SettingsHandler.getPlayAlarm());
    //jComboBox1.setSelectedIndex(getIndexOfProvider(SettingsHandler.getProvider()));
    jComboBox2.setSelectedIndex(getIndexOfEvent(SettingsHandler.getExpo()));
    jTextField1.setText(SettingsHandler.getEmail());
    java.awt.Dimension d = jTextField2.getSize();
    String cellnum = SettingsHandler.getCellNumber();
    if (cellnum.contains(";")) {
      System.out.println("Debug: All = " + cellnum);
      String[] specificNumbers = cellnum.replaceAll("; ", ";").split(";");
      jComboBox1.setSelectedIndex(Setup.getIndexOfProvider(Email.getProvider(specificNumbers[0].substring(specificNumbers[0].indexOf("@")))));
      if (Email.getProvider(specificNumbers[0].substring(specificNumbers[0].indexOf("@"))).equals("[Other]")) {
        jTextField2.setText(specificNumbers[0].trim());
      } else {
        jTextField2.setText(specificNumbers[0].substring(0, specificNumbers[0].indexOf("@")).trim());
      }
      jTextField2.setCaretPosition(0);
      for (int a = 1; a < specificNumbers.length; a++) {
        System.out.println("specificNumbers[" + a + "] = " + specificNumbers[a]);
        addPhonePanel(new ExtraPhonePanel(this, Email.splitEmail(specificNumbers[a])[0].trim(), Email.splitEmail(specificNumbers[a])[1].trim()));
      }
    } else {
      System.out.println("Normal address");
      jTextField2.setText(cellnum);
    }
    jTextField2.setSize(d);
    System.out.println("Prefs loading time = " + (System.nanoTime() - tS) + " Nanoseconds");
    if (SettingsHandler.getSavePrefs()) {
      JCBSavePreferences.setSelected(SettingsHandler.getSavePrefs());
      JCBSaveCellnum.setSelected(SettingsHandler.getSaveCellnum());
      JCBSaveCheckPax.setSelected(SettingsHandler.getSavePax());
      JCBSaveCheckShowclix.setSelected(SettingsHandler.getSaveShowclix());
      JCBSaveEvent.setSelected(SettingsHandler.getSaveEvent());
      JCBSavePlayAlarm.setSelected(SettingsHandler.getSaveAlarm());
      JCBSaveProvider.setSelected(SettingsHandler.getSaveProvider());
      JCBSaveRefreshTime.setSelected(SettingsHandler.getSaveRefreshTime());
      JCBSaveEmail.setSelected(SettingsHandler.getSaveEmail());
    } else {
      JCBSaveCellnum.setEnabled(false);
      JCBSaveCheckPax.setEnabled(false);
      JCBSaveCheckShowclix.setEnabled(false);
      JCBSaveEvent.setEnabled(false);
      JCBSavePlayAlarm.setEnabled(false);
      JCBSaveProvider.setEnabled(false);
      JCBSaveRefreshTime.setEnabled(false);
      JCBSaveEmail.setEnabled(false);
    }
  }

  public void addPhonePanel(ExtraPhonePanel panel) {
    extraPhonePanelList.add(panel);
    JPPhonePanel.add(panel);
    JPPhonePanel.revalidate();
    pack();
  }

  public void removePhonePanel(ExtraPhonePanel panel) {
    extraPhonePanelList.remove(panel);
    JPPhonePanel.remove(panel);
    JPPhonePanel.revalidate();
    pack();
  }

  public static final int getIndexOfEvent(String eventName) {
    switch (eventName.toLowerCase()) {
      case "pax prime":
      default:
        return 0;
      case "pax east":
        return 1;
      case "pax south":
        return 2;
      case "pax aus":
        return 3;
    }
  }

  public static final int getIndexOfProvider(String provider) {
    switch (provider.toLowerCase()) {
      case "at&t":
      default:
        return 0;
      case "verizon":
        return 1;
      case "sprint":
        return 2;
      case "t-mobile":
        return 3;
      case "u.s. cellular":
        return 4;
      case "[other]":
        return 5;
    }
  }

  public void setPatchNotesText(final String text) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jTextArea4.setText(text);
        jTextArea4.setCaretPosition(0);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jPasswordField1 = new javax.swing.JPasswordField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jComboBox1 = new javax.swing.JComboBox();
    jLabel6 = new javax.swing.JLabel();
    jSlider1 = new javax.swing.JSlider();
    jButton1 = new javax.swing.JButton();
    jCheckBox1 = new javax.swing.JCheckBox();
    jCheckBox2 = new javax.swing.JCheckBox();
    jCheckBox3 = new javax.swing.JCheckBox();
    jComboBox2 = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    JPPhonePanel = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    jScrollPane5 = new javax.swing.JScrollPane();
    jTextPane1 = new javax.swing.JTextPane();
    jPanel4 = new javax.swing.JPanel();
    jScrollPane4 = new javax.swing.JScrollPane();
    jTextArea4 = new javax.swing.JTextArea();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane6 = new javax.swing.JScrollPane();
    jTextPane2 = new javax.swing.JTextPane();
    jPanel5 = new javax.swing.JPanel();
    JCBSavePreferences = new javax.swing.JCheckBox();
    JCBSaveEmail = new javax.swing.JCheckBox();
    JCBSaveCellnum = new javax.swing.JCheckBox();
    JCBSaveProvider = new javax.swing.JCheckBox();
    JCBSaveRefreshTime = new javax.swing.JCheckBox();
    JCBSaveCheckPax = new javax.swing.JCheckBox();
    JCBSaveCheckShowclix = new javax.swing.JCheckBox();
    JCBSavePlayAlarm = new javax.swing.JCheckBox();
    JCBSaveEvent = new javax.swing.JCheckBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("PAX Checker Setup");
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("PAX Checker Setup");

    jLabel2.setText("Email");

    jTextField1.setToolTipText("<html>\nEmail address to send texts with. Currently,<br>\nonly Yahoo! and Gmail are supported.<br>\nPut your full email addres in, otherwise it<br>\ndefaults to @yahoo.com.<br>\nSee the Instructions tab for how to use emails<br>\nother than Yahoo! or Gmail.\n</html>");

    jLabel3.setText("Password");

    jLabel4.setText("Cell Num");

    jTextField2.setToolTipText("<html>\nSpecify the number you want to receive texts at.<br>\nOnly put your number - no spaces, no leading 1.<br>\nYou may use dashes -- or perentheses ().<br>\nIf you use a different carrier, you may find their<br>\ntexting email address extension at<br>\nwww.emailtextmessages.com and put it onto the<br>\nend of your number.<br>\nExamples:<br>\n(123)-456-7890 [Verizon selected in dropdown box]<br>\n1234567890@car.rier.net<br>\n123-4567890@car.rier.net<br>\n</html>");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AT&T", "Verizon", "Sprint", "T-Mobile", "U.S. Cellular", "[Other]" }));

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Seconds Between Website Checks");

    jSlider1.setMajorTickSpacing(10);
    jSlider1.setMaximum(60);
    jSlider1.setMinimum(10);
    jSlider1.setMinorTickSpacing(2);
    jSlider1.setPaintLabels(true);
    jSlider1.setPaintTicks(true);
    jSlider1.setPaintTrack(false);
    jSlider1.setSnapToTicks(true);
    jSlider1.setValue(10);

    jButton1.setText("START!");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jCheckBox1.setSelected(true);
    jCheckBox1.setText("Scan PAX Registration website");
    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox1ActionPerformed(evt);
      }
    });

    jCheckBox2.setSelected(true);
    jCheckBox2.setText("Scan Showclix website");
    jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox2ActionPerformed(evt);
      }
    });

    jCheckBox3.setText("Play Alarm when Tickets Found");
    jCheckBox3.setToolTipText("<html>\nIf checked, the program will play a sound when an update to<br>\nthe PAX Prime website OR the Showclix website (whichever one(s)<br>\nyou have enabled) is found.\n</html>");

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PAX Prime", "PAX East", "PAX South", "PAX Aus" }));

    jLabel5.setText("PAX Expo to Check");

    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

    javax.swing.GroupLayout JPPhonePanelLayout = new javax.swing.GroupLayout(JPPhonePanel);
    JPPhonePanel.setLayout(JPPhonePanelLayout);
    JPPhonePanelLayout.setHorizontalGroup(
      JPPhonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    JPPhonePanelLayout.setVerticalGroup(
      JPPhonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    jButton2.setText("Add Another Phone Number");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextField1)
              .addComponent(jPasswordField1)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addComponent(JPPhonePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jCheckBox3)
              .addComponent(jCheckBox2)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, 0)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(JPPhonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addGap(0, 0, 0)
        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap())
    );

    JPPhonePanel.setLayout(new javax.swing.BoxLayout(JPPhonePanel, javax.swing.BoxLayout.Y_AXIS));

    jTabbedPane1.addTab("Setup", jPanel1);

    jTextPane1.setBorder(null);
    jTextPane1.setContentType("text/html"); // NOI18N
    jTextPane1.setEditable(false);
    jTextPane1.setEditorKit(javax.swing.JEditorPane.createEditorKitForContentType("text/html"));
    jTextPane1.setText("<html>\n    <body>\n        <em>If there is a horizontal scrollbar here, please let\n            <a href=\"http://www.reddit.com/user/SunnyBat\">/u/SunnyBat</a> know!</em>\n\n        <h1>Important Note</h1>\n        You should NOT rely on only one way of PAX Ticket sale notifications.\n        Sign up for the @Official_PAX Twitter notifications\n        <a href=\"https://support.twitter.com/articles/20170004-fast-following-on-sms\">via text</a>.\n        Watch the Reddit Live thread (if there is one). Make sure your friends\n        know to text you if they find out. Do NOT miss out because you relied on only\n        one form of notification!<br>\n        That being said, this program worked perfectly last year. It detected\n        the Showclix link as soon as it went up -- a few minutes before the\n        Twitter notification.\n\n        <h1>Email and Password</h1>\n        <b>If you do not want to receive a text message when tickets are found,\n            simply leave these fields blank.</b><br>\n        Your email is used to send a text message when tickets are found. Currently,\n        there are two internally supported email services: <b>Gmail</b> and <b>Yahoo!</b>.\n        Simply type in your email address to use these. For information on using\n        different email services, see the Additional Information section.<br>\n        Gmail generally takes 30-45 seconds to receive a sent text. <em>This is\n            the recommended option.</em><br>\n        Yahoo! is very inconsistent with texts -- it can take anywhere from 10\n        <em>seconds</em> to 15 <em>minutes</em> to receive a text from Yahoo!<br>\n        <em>For information on why your email is required, see the Additional\n            Information section.</em><br>\n\n        <h1>Cell Number</h1>\n        Your cell number is required to text to your phone. The program natively\n        supports AT&T, Verizon, Sprint, T-Mobile, and U.S. Cellular. If you have\n        any of these carriers, simply select yours from the dropdown menu.\n        If you have a different carrier, you'll need to go to\n        <a href=\"http://www.emailtextmessages.com\">emailtextmessages.com</a> and\n        get the ending for your carrier.<br>\n        You can put dashes and parentheses into your number. For example, 012-345-6789\n        is just as valid as (012)-345-6789. Your number is converted\n        into a format with no dashes or parentheses -- just numbers. Overall,\n        the email is sent in the format of 0123456789@car.rier.net. For example,\n        if your number is 0123456789 and your provider is 3 River Wireless,\n        you would put 0123456789@sms.3rivers.net in the Cell Num field.<br>\n        <em>For information on sending a text to multiple numbers, please see\n            the Additional Information section.</em>\n\n        <h1>Scan PAX Registration Website</h1>\n        This scans the selected PAX registration website for the \"Register Now\" button.\n        It checks PAX.paxsite.com/registration (obviously PAX is the expo you're checking).<br>\n        This uses the most bandwidth (still not very much). It's recommended to\n        use this option if you really want tickets.\n\n        <h1>Scan Showclix Website</h1>\n        This scans the Showclix API (<a href=\"https://api.showclix.com\">api.showclix.com</a>) for the\n        selected PAX expo's most recent ticket sale.<br>\n        <b>This option is highly recommended.</b> The Showclix website is updated first in order\n        to get the link to the ticket queue, which this program finds using the Showclix API. It\n        uses a small amount of bandwidth, and will mostly likely find the tickets before the PAX\n        Registration Website option.<br>\n        Credit goes to <a href=\"http://www.reddit.com/user/GrahamArthurBlair\">/u/GrahamArthurBlair</a>\n        for his original Showclix API scanning code.<br><br>\n\n\n        <h1>Additional Information</h1>\n\n        <h2>Why Does This Need my Password?</h2>\n        An email is required to send a text message. It's the simplest way to send\n        a text message, and anyone can use it.<br>\n        There are several reasons why your email and password is required:\n        <ul>\n            <li>You must authenticate your login to send an email using your account\n                username and password</li>\n            <li>This program is open-source. If there was a hard-coded username and\n                password, anyone would be able to find it in this program at any time and\n                disable texting for everyone. Using your email address prevents this from\n                happening.</li>\n            <li>Having one email address send out potentially dozens (modestly) of\n                emails within 60 seconds is very fishy, and multiple logins from different\n                locations will lock out the email after a few emails. This means only a few\n                people would actually get the text.</li>\n            <li>You will recognize the sender of your text</li>\n        </ul>\n\n        <h2>Using a Different Email Provider</h2>\n        For sending an email using a different email provider, several things are required:\n        <ul>\n            <li>The service must use SMTP and TLS</li>\n            <li>You must know the SMTP server address</li>\n            <li>You must know the SMTP server port</li>\n        </ul>\n        Once you have this information, you must input this after your email address\n        and two colons (::). If the server uses a port other than 587, you must\n        add the port after the server and a colon (:).<br>\n        An example:<br>\n        Emailaddress@someprovider.com::provider.smpt.server:999<br>\n        <b>Note that this is very experimental. Make sure to test your text message every time!</b>\n\n        <h2>Text Multiple Numbers at Once</h2>\n        To text multiple numbers at once:<br>\n        <ul>\n            <li>Separate each number with a semicolon (;)</li>\n            <li>You're able to choose <em>one</em> cell carrier to send to. Every\n                other carrier MUST have the email ending from <a href=\"http://www.emailtextmessages.com\">emailtextmessages.com</a>,\n                regardless of whether or not the program supports it!</li>\n            <li>You're only able to put spaces after semicolons. Anywhere else could\n                result in one or more incorrect text emails being sent.</li>\n        </ul>\n        Example (with Verizon selected):<br>\n        0123456789@mms.att.net; (123)4567890;234-567-8901@tmomail.net; 3456789012<br>\n        All the numbers without an @car.rier.net extension will be defaulted to\n        Verizon numbers, as Verizon was selected.\n    </body>\n</html>");
    jTextPane1.setCaretPosition(0);
    jTextPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
      public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent e) {
        if (e.getEventType() == javax.swing.event.HyperlinkEvent.EventType.ACTIVATED) {
          Browser.openLinkInBrowser(e.getURL());
        }
      }
    });
    jScrollPane5.setViewportView(jTextPane1);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Instructions", jPanel6);

    jTextArea4.setEditable(false);
    jTextArea4.setColumns(20);
    jTextArea4.setLineWrap(true);
    jTextArea4.setRows(5);
    jTextArea4.setText("Loading patch notes, please wait...");
    jTextArea4.setWrapStyleWord(true);
    jScrollPane4.setViewportView(jTextArea4);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Patch Notes", jPanel4);

    jTextPane2.setBorder(null);
    jTextPane2.setContentType("text/html"); // NOI18N
    jTextPane2.setEditable(false);
    jTextPane2.setEditorKit(javax.swing.JEditorPane.createEditorKitForContentType("text/html"));
    jTextPane2.setText("<html>\n    <body>\n        <em>If there is a horizontal scrollbar here, please let\n            <a href=\"https://www.reddit.com/user/SunnyBat\">/u/SunnyBat</a> know!</em>\n\n        <h1>External Links</h1>\n        <ul>\n            <li>This program has been provided for free. If you have been charged for it, get your money back and contact me immediately!</li>\n            <li>The source code can be found <a href=\"https://www.github.com/SunnyBat/PAXChecker\">on GitHub</a>.</li>\n            <li>Program published on <a href=\"https://www.github.com/SunnyBat/PAXChecker\">/r/PAX</a> -- If you see it somewhere else, please let me know!</li>\n        </ul>\n\n        <h1>Credits</h1>\n        <ul>\n            <li>Program created by <a href=\"https://www.reddit.com/user/SunnyBat\">/u/SunnyBat</a></li>\n            <li>Showclix API scanning code originally created by <a href=\"https://www.reddit.com/user/GrahamArthurBlair\">/u/GrahamArthurBlair</a></li>\n            <li>Reddit Gold guilders: You're all awesome. If you want me to put your name here, let me know!</li>\n            <li><a href=\"https://java.net/projects/javamail/pages/Home\">JavaMail 1.4.7</a> -- For sending emails</li>\n            <li><a href=\"https://code.google.com/p/json-simple/\">JSON.simple</a> -- For parsing Showclix API JSON responses</li>\n        </ul>\n\n        <h1>Contact Me</h1>\n        To contact me, please use one of the following methods:\n        <ul>\n            <li><a href=\"mailto:Sunnybat@yahoo.com\">Email me</a></li>\n            <li><a href=\"https://www.reddit.com/message/compose/?to=SunnyBat\">Message me on Reddit</a></li>\n            <li><a href=\"https://github.com/SunnyBat\">Message me on Github</a></li>\n        </ul>\n    </body>\n</html>");
    jTextPane2.setToolTipText("");
    jTextPane2.setCaretPosition(0);
    jTextPane2.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
      public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent e) {
        if (e.getEventType() == javax.swing.event.HyperlinkEvent.EventType.ACTIVATED) {
          Browser.openLinkInBrowser(e.getURL());
        }
      }
    });
    jScrollPane6.setViewportView(jTextPane2);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Extra", jPanel3);

    JCBSavePreferences.setText("Save Preferences");
    JCBSavePreferences.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JCBSavePreferencesActionPerformed(evt);
      }
    });

    JCBSaveEmail.setText("Save Username");

    JCBSaveCellnum.setText("Save Cell Number");
    JCBSaveCellnum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JCBSaveCellnumActionPerformed(evt);
      }
    });

    JCBSaveProvider.setText("Save Provider");

    JCBSaveRefreshTime.setText("Save Refresh Time");

    JCBSaveCheckPax.setText("Save PAX Checking");

    JCBSaveCheckShowclix.setText("Save Showclix Checking");

    JCBSavePlayAlarm.setText("Save Play Alarm");

    JCBSaveEvent.setText("Save Event");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("Preferences are saved after you start the program. You may choose which preferences you want saved. If you do not save a preference, it loads in its default state.\n\nNote that your password is NEVER saved using Preferences.");
    jTextArea1.setWrapStyleWord(true);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(JCBSaveEvent)
              .addComponent(JCBSavePreferences)
              .addComponent(JCBSaveEmail)
              .addComponent(JCBSaveCellnum)
              .addComponent(JCBSaveProvider)
              .addComponent(JCBSaveCheckPax)
              .addComponent(JCBSaveCheckShowclix)
              .addComponent(JCBSavePlayAlarm)
              .addComponent(JCBSaveRefreshTime))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(JCBSavePreferences)
        .addGap(18, 18, 18)
        .addComponent(JCBSaveEmail)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JCBSaveCellnum)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JCBSaveProvider)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(JCBSaveCheckPax)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JCBSaveCheckShowclix)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JCBSavePlayAlarm)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JCBSaveRefreshTime)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(JCBSaveEvent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Preferences", jPanel5);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    // TODO add your handling code here:
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
          jButton1.setEnabled(false);
        } else {
          jButton1.setEnabled(true);
        }
      }
    });
  }//GEN-LAST:event_jCheckBox2ActionPerformed

  private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
          jButton1.setEnabled(false);
        } else {
          jButton1.setEnabled(true);
        }
      }
    });
  }//GEN-LAST:event_jCheckBox1ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    jButton1.setText("Starting, please wait...");
    jButton1.setEnabled(false);
    if (jCheckBox1.isSelected()) {
      Browser.enablePaxWebsiteChecking();
    } else {
      if (!jCheckBox2.isSelected()) {
        return;
      }
    }
    if (jCheckBox2.isSelected()) {
      Browser.enableShowclixWebsiteChecking();
    }
    Audio.setPlayAlarm(jCheckBox3.isSelected());
    Email.setUsername(jTextField1.getText());
    Email.setPassword(new String(jPasswordField1.getPassword()));
    Browser.setExpo(jComboBox2.getSelectedItem().toString());
    Browser.setWebsiteLink(Browser.getWebsiteLink(Browser.getExpo()));
    String text = jTextField2.getText();
    if (!text.contains("@")) {
      text += Email.getCarrierExtension(jComboBox1.getSelectedItem().toString());
    }
    String tempText;
    java.util.Iterator<ExtraPhonePanel> myIt = extraPhonePanelList.iterator();
    while (myIt.hasNext()) {
      ExtraPhonePanel panel = myIt.next();
      tempText = panel.getNumber();
      if (tempText.length() < 4) {
        System.out.println("NOTE: Number is too short! Cannot use!");
        continue;
      }
      String[] split = tempText.split(";");
      tempText = "";
      for (String split1 : split) {
        split1 = split1.trim();
        tempText += split1;
        if (!split1.contains("@")) {
          tempText += Email.getCarrierExtension(panel.getProvider());
        }
        tempText += ";";
      }
      //Validate tempText address?
      text += ";" + tempText;
      System.out.println("Debug: " + tempText);
    }
    System.out.println("Final Text: " + text);
    Email.addEmailAddress(text);
    PAXChecker.setRefreshTime(jSlider1.getValue());
    SettingsHandler.setSavePrefs(JCBSavePreferences.isSelected());
    if (JCBSavePreferences.isSelected()) {
      SettingsHandler.setSaveCellnum(JCBSaveCellnum.isSelected());
      SettingsHandler.setSavePax(JCBSaveCheckPax.isSelected());
      SettingsHandler.setSaveShowclix(JCBSaveCheckShowclix.isSelected());
      SettingsHandler.setSaveEvent(JCBSaveEvent.isSelected());
      SettingsHandler.setSaveAlarm(JCBSavePlayAlarm.isSelected());
      SettingsHandler.setSaveProvider(JCBSaveProvider.isSelected());
      SettingsHandler.setSaveRefreshTime(JCBSaveRefreshTime.isSelected());
      SettingsHandler.setSaveEmail(JCBSaveEmail.isSelected());
    }
    this.dispose();
    PAXChecker.startCheckingWebsites();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void JCBSaveCellnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBSaveCellnumActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_JCBSaveCellnumActionPerformed

  private void JCBSavePreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBSavePreferencesActionPerformed
    // TODO add your handling code here:
    boolean selected = JCBSavePreferences.isSelected();
    JCBSaveCellnum.setEnabled(selected);
    JCBSaveCheckPax.setEnabled(selected);
    JCBSaveCheckShowclix.setEnabled(selected);
    JCBSaveEmail.setEnabled(selected);
    JCBSaveEvent.setEnabled(selected);
    JCBSavePlayAlarm.setEnabled(selected);
    JCBSaveProvider.setEnabled(selected);
    JCBSaveRefreshTime.setEnabled(selected);
  }//GEN-LAST:event_JCBSavePreferencesActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    addPhonePanel(new ExtraPhonePanel(this));
  }//GEN-LAST:event_jButton2ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox JCBSaveCellnum;
  private javax.swing.JCheckBox JCBSaveCheckPax;
  private javax.swing.JCheckBox JCBSaveCheckShowclix;
  private javax.swing.JCheckBox JCBSaveEmail;
  private javax.swing.JCheckBox JCBSaveEvent;
  private javax.swing.JCheckBox JCBSavePlayAlarm;
  private javax.swing.JCheckBox JCBSavePreferences;
  private javax.swing.JCheckBox JCBSaveProvider;
  private javax.swing.JCheckBox JCBSaveRefreshTime;
  private javax.swing.JPanel JPPhonePanel;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JCheckBox jCheckBox3;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPasswordField jPasswordField1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea4;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextPane jTextPane1;
  private javax.swing.JTextPane jTextPane2;
  // End of variables declaration//GEN-END:variables
}
