package paxchecker.tickets;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author SunnyBat
 */
public class Tickets extends javax.swing.JFrame {

  public Tickets(final String link) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        initComponents();
        String newline = System.getProperty("line.separator");
        jTextArea1.append(newline + newline + "Tickets found at " + currentTime() + newline + "NOTE: The hours in this time may be off... The minutes and seconds are correct!");
        jTextArea1.append(newline + newline + "URL found: " + link);
        setAlwaysOnTop(true);
        setVisible(true);
        toFront();
        requestFocus();
      }
    });
  }

  public static String currentTime() {
    Calendar myCal = Calendar.getInstance();
    long ctm = myCal.getTimeInMillis();
    if (myCal.getTimeZone().getRawOffset() != -28800000) {
      System.out.println("NOTE: Timezone is NOT in PST! Time will be converted to PST. (Test feature, verify times)");
      ctm += -28800000 - myCal.getTimeZone().getRawOffset(); // Test lol, not sure if it will work or not
    }
    ctm -= 28800000; // PST is 8 hours behind UST -- adjust time accordingly
    /*
     * ctm + inDaylightTime == Account for Daylight Savings Time
     * ctm / 1000 / 60 / 60 == Convert CurrentTimeMillis to seconds->minutes->hours
     * * 60 == Convert hours to minutes
     * % (24*60) == Take off time to cover only today, formatTime also converts 0 hourMinutes into 12:00 AM
     */
    long hourMinutes = ((((ctm / 1000 / 60 / 60)) * 60) + (myCal.getTimeZone().inDaylightTime(new Date()) ? 60 : 0)) % (24 * 60);
    long minutes = (ctm / 1000 / 60) % 60;
    long seconds = (ctm / 1000) % 60;
    int hours = (int) (hourMinutes / 60) % 12;
    if (hours == 0) {
      hours = 12;
    }
    return hours + ":" + minutes + ":" + seconds;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("PAX On Sale!");
    setResizable(false);

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
    jTextArea1.setForeground(new java.awt.Color(255, 51, 0));
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("An update has been found!\n\nAn attempt to open the link found in your default browser has been made. If it did not open, you will have to do so manually.\n\nGood luck buying tickets!\n- /u/SunnyBat (Sunnybat@yahoo.com)");
    jTextArea1.setWrapStyleWord(true);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
